import {
  AlertTriangle,
  CheckCircle2,
  ChevronDown,
  Info,
} from "lucide-react";

import { useState } from "react";

function SignalList({ signals }) {
  if (!signals || signals.length === 0) {
    return (
      <section className="rounded-2xl border border-zinc-800 bg-zinc-900/50">
        <div className="flex items-center gap-3 p-5">
          <CheckCircle2
            size={18}
            className="text-zinc-500"
          />

          <div>
            <h3 className="text-sm font-semibold">
              No Signals Detected
            </h3>

            <p className="mt-1 text-xs text-zinc-600">
              No deterministic comparison rule was triggered.
            </p>
          </div>
        </div>
      </section>
    );
  }

  return (
    <section className="rounded-2xl border border-zinc-800 bg-zinc-900/50">
      <div className="border-b border-zinc-800 px-5 py-4">
        <div className="flex items-center gap-2">
          <AlertTriangle
            size={16}
            className="text-zinc-400"
          />

          <div>
            <h3 className="text-sm font-semibold">
              Detected Signals
            </h3>

            <p className="mt-1 text-xs text-zinc-600">
              Signals generated by deterministic comparison rules.
            </p>
          </div>
        </div>
      </div>

      <div className="divide-y divide-zinc-800">
        {signals.map((signal, index) => (
          <SignalItem
            key={`${signal.type}-${index}`}
            signal={signal}
          />
        ))}
      </div>
    </section>
  );
}

function SignalItem({ signal }) {
  const [expanded, setExpanded] = useState(false);

  const severityClass = {
    HIGH: "border-zinc-600 bg-zinc-800 text-zinc-200",
    MEDIUM: "border-zinc-700 bg-zinc-900 text-zinc-400",
    LOW: "border-zinc-800 bg-zinc-950 text-zinc-500",
  };

  return (
    <div className="p-5">
      <div className="flex gap-4">

        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-zinc-800">
          <AlertTriangle
            size={16}
            className="text-zinc-400"
          />
        </div>

        <div className="min-w-0 flex-1">

          <div className="flex flex-wrap items-center gap-2">
            <h4 className="text-sm font-semibold">
              {signal.title}
            </h4>

            <span
              className={`rounded-full border px-2 py-0.5 text-[10px] font-medium ${
                severityClass[signal.severity] ||
                severityClass.LOW
              }`}
            >
              {signal.severity}
            </span>
          </div>

          <p className="mt-2 text-sm leading-6 text-zinc-500">
            {signal.description}
          </p>

          <div className="mt-3 flex flex-wrap items-center gap-3">
            <span className="text-[10px] uppercase tracking-wider text-zinc-700">
              Confidence
            </span>

            <div className="h-1.5 w-24 overflow-hidden rounded-full bg-zinc-800">
              <div
                className="h-full rounded-full bg-zinc-500"
                style={{
                  width: `${Math.round(
                    (signal.confidence || 0) * 100
                  )}%`,
                }}
              />
            </div>

            <span className="text-[10px] text-zinc-600">
              {Math.round(
                (signal.confidence || 0) * 100
              )}
              %
            </span>
          </div>

          {signal.evidence?.length > 0 && (
            <button
              onClick={() => setExpanded(!expanded)}
              className="mt-4 flex items-center gap-1.5 text-xs text-zinc-500 transition hover:text-zinc-300"
            >
              <Info size={13} />

              {signal.evidence.length} evidence item
              {signal.evidence.length !== 1 ? "s" : ""}

              <ChevronDown
                size={13}
                className={`transition-transform ${
                  expanded ? "rotate-180" : ""
                }`}
              />
            </button>
          )}

          {expanded && (
            <div className="mt-3 space-y-2">
              {signal.evidence.map((evidence, index) => (
                <EvidenceCard
                  key={index}
                  evidence={evidence}
                />
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function EvidenceCard({ evidence }) {
  return (
    <div className="rounded-xl border border-zinc-800 bg-zinc-950/60 p-3">
      <div className="flex flex-wrap gap-x-4 gap-y-1">
        <div>
          <p className="text-[9px] uppercase tracking-wider text-zinc-700">
            Source
          </p>

          <p className="mt-0.5 text-xs text-zinc-500">
            {evidence.source || "—"}
          </p>
        </div>

        <div>
          <p className="text-[9px] uppercase tracking-wider text-zinc-700">
            Field
          </p>

          <p className="mt-0.5 text-xs text-zinc-500">
            {evidence.field || "—"}
          </p>
        </div>

        <div>
          <p className="text-[9px] uppercase tracking-wider text-zinc-700">
            Value
          </p>

          <p className="mt-0.5 text-xs font-medium text-zinc-300">
            {evidence.value ?? "—"}
          </p>
        </div>
      </div>

      {evidence.comparison && (
        <p className="mt-2 border-t border-zinc-800 pt-2 text-[11px] text-zinc-600">
          {evidence.comparison}
        </p>
      )}
    </div>
  );
}

export default SignalList;