"""Initial durable research schema

Revision ID: 5484f418611b
Revises:
"""
from alembic import op
import sqlalchemy as sa


revision = '5484f418611b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('official_domains', sa.JSON(), nullable=False),
    sa.Column('identity_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('identity_reference', sa.Text(), nullable=False),
    sa.Column('comparison_note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_table('credit_accounts',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('workspace_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('user_company', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_created_at'), 'watchlists', ['created_at'], unique=False)
    op.create_index(op.f('ix_watchlists_workspace_id'), 'watchlists', ['workspace_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('workspace_id', sa.String(length=80), nullable=False),
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('baseline_id', sa.String(length=36), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('external_calls', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'idempotency_key', name='uq_run_idempotency')
    )
    op.create_index(op.f('ix_research_runs_created_at'), 'research_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_runs_status'), 'research_runs', ['status'], unique=False)
    op.create_index(op.f('ix_research_runs_watchlist_id'), 'research_runs', ['watchlist_id'], unique=False)
    op.create_index(op.f('ix_research_runs_workspace_id'), 'research_runs', ['workspace_id'], unique=False)
    op.create_index('uq_active_run', 'research_runs', ['watchlist_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running')"), sqlite_where=sa.text("status IN ('queued', 'running')"))
    op.create_table('signals',
    sa.Column('workspace_id', sa.String(length=80), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'mode', 'event_key')
    )
    op.create_index(op.f('ix_signals_company_id'), 'signals', ['company_id'], unique=False)
    op.create_index(op.f('ix_signals_created_at'), 'signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_signals_workspace_id'), 'signals', ['workspace_id'], unique=False)
    op.create_table('sources',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('extraction', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_sources_company_id'), 'sources', ['company_id'], unique=False)
    op.create_index(op.f('ix_sources_created_at'), 'sources', ['created_at'], unique=False)
    op.create_table('watchlist_companies',
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'company_id')
    )
    op.create_table('credit_reservations',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('request_key', sa.String(length=64), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_reservations_created_at'), 'credit_reservations', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_reservations_run_id'), 'credit_reservations', ['run_id'], unique=False)
    op.create_table('run_steps',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'attempt', 'sequence')
    )
    op.create_index(op.f('ix_run_steps_created_at'), 'run_steps', ['created_at'], unique=False)
    op.create_index(op.f('ix_run_steps_run_id'), 'run_steps', ['run_id'], unique=False)
    op.create_table('signal_revisions',
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('prior_revision_id', sa.String(length=36), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('card', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prior_revision_id'], ['signal_revisions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'run_id')
    )
    op.create_index(op.f('ix_signal_revisions_created_at'), 'signal_revisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_signal_revisions_run_id'), 'signal_revisions', ['run_id'], unique=False)
    op.create_index(op.f('ix_signal_revisions_severity'), 'signal_revisions', ['severity'], unique=False)
    op.create_index(op.f('ix_signal_revisions_signal_id'), 'signal_revisions', ['signal_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('request_key', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized', sa.JSON(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.String(length=100), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_company_id'), 'snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_snapshots_created_at'), 'snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_snapshots_request_key'), 'snapshots', ['request_key'], unique=False)
    op.create_table('evidence',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=100), nullable=False),
    sa.Column('locator', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.String(length=100), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['signal_revisions.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_created_at'), 'evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_revision_id'), 'evidence', ['revision_id'], unique=False)
    op.create_table('provider_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('run_snapshots',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('run_id', 'snapshot_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_snapshots')
    op.drop_table('provider_cache')
    op.drop_index(op.f('ix_evidence_revision_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_created_at'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_snapshots_request_key'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_created_at'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_company_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_signal_revisions_signal_id'), table_name='signal_revisions')
    op.drop_index(op.f('ix_signal_revisions_severity'), table_name='signal_revisions')
    op.drop_index(op.f('ix_signal_revisions_run_id'), table_name='signal_revisions')
    op.drop_index(op.f('ix_signal_revisions_created_at'), table_name='signal_revisions')
    op.drop_table('signal_revisions')
    op.drop_index(op.f('ix_run_steps_run_id'), table_name='run_steps')
    op.drop_index(op.f('ix_run_steps_created_at'), table_name='run_steps')
    op.drop_table('run_steps')
    op.drop_index(op.f('ix_credit_reservations_run_id'), table_name='credit_reservations')
    op.drop_index(op.f('ix_credit_reservations_created_at'), table_name='credit_reservations')
    op.drop_table('credit_reservations')
    op.drop_table('watchlist_companies')
    op.drop_index(op.f('ix_sources_created_at'), table_name='sources')
    op.drop_index(op.f('ix_sources_company_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_signals_workspace_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_created_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_company_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index('uq_active_run', table_name='research_runs', postgresql_where=sa.text("status IN ('queued', 'running')"), sqlite_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index(op.f('ix_research_runs_workspace_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_watchlist_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_status'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_created_at'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_watchlists_workspace_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_created_at'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_table('credit_accounts')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
